### ISSUE TITLE
Unable to get translations for Cuba 7.1.2

### ISSUE THREAD

**Issue by tdltdl** [cuba-platform/translations#62]
The add-on is not listed - prbably because of compatibility with 7.0 only - or the add-on install button shows incorrect information (says to simply go to add-on and install it)

**Comment by pfurini** [comment]
Hi, this is not an add-on, it is a repository to collect all the messages* files for each version/language combination.
Search for user-contributed add-ons in the marketplace, for example:
- https://www.cuba-platform.com/marketplace/italian-translation/
- https://www.cuba-platform.com/marketplace/german-localization/

If there's no specific add-on for your language, you need to follow the instructions in the README of this repo, in order to manually add the relevant message files to your project.

**Comment by tdltdl** [comment]
My point is that in the add-on section of the web site it is mentioned. 

![image](https://user-images.githubusercontent.com/14175340/68837388-bba51d00-06bc-11ea-8083-29a692e8b878.png)

So this can be misleading. But as I understand it is more a web-site content issue than a add-on issue (even if it might be more convenient to handle the translations as a "normal" plugin for ease of use)
